version: '3'
services:
  app:
    image: my-node-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://shanmukasagar:sagar%4005@cluster0.3bton.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"